# Site settings
title: "Big Cove Consulting"
email: "info@bigcove.io"
description: > Specializing in technology consulting offering end-to-end solutions in software development, web applications, and embedded systems across multiple industries. With expertise in product design, development, and post-launch support, I guide clients from concept to implementation, including hardware specification and design for embedded systems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "bigcove.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
